### ISSUE TITLE
Can't Clear Storage

### ISSUE THREAD

**Issue by bam80** [DiMartinoXBMC/plugin.video.torrenter#3]
Got Error while trying to Clear Storage from Torrenter Global Control Center menu.
Perhaps it is due russian symbols in downloaded folders names:
```
19:30:43 T:140342795945728  NOTICE: -->Python Interpreter Initialized<--
19:30:43 T:140342795945728  NOTICE: Torrenter v.2.3.7c
19:30:43 T:140342795945728  NOTICE: SYS ARGV: ['plugin://plugin.video.torrenter/', '-1', '?action=clearStorage']
19:30:43 T:140342795945728  NOTICE: !!!!!!!!!!!!!!!!!! BORN Core
19:30:43 T:140342795945728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.torrenter/default.py", line 40, in <module>
                                                core.executeAction(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1041, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1210, in clearStorage
                                                clearStorage(self.userStorageDirectory)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/functions.py", line 81, in clearStorage
                                                shutil.rmtree(userStorageDirectory, ignore_errors=True)
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Generic.x86_64-5.95.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
                                              File "/home/stephan/projects/openelec-6.0/build.OpenELEC-Generic.x86_64-5.95.3/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 71, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)
                                            -->End of Python script error report<--
19:30:45 T:140342795945728  NOTICE: Thread LanguageInvoker start, auto delete: false
```

**Comment by DiMartinoXBMC** [comment]
https://github.com/DiMartinoXBMC/plugin.video.torrenter/commit/e7693e56980c73994562fc72f42f7ff4ec7bea76 should fix that
