### ISSUE TITLE
[OpenELEC] Can't download torrent using libtorrent

### ISSUE THREAD

**Issue by bam80** [DiMartinoXBMC/plugin.video.torrenter#4]
When trying to download, error occurs:
```
21:56:15 T:140342326183680  NOTICE: ### [LibTorrent v.0.16.19hb]: Imported libtorrent v1.0.6.0 from "/storage/.kodi/temp/xbmcup/script.module.libtorrent/python_libtorrent/linux_x86_64/1.0.6"
21:56:15 T:140342326183680  NOTICE: ### [Torrenter v.2.3.7c]: Imported libtorrent v1.0.6.0 from python_libtorrent/linux_x86_64
21:56:15 T:140342326183680  NOTICE: ### [Torrenter v.2.3.7c]: Encryption enabling...
21:56:15 T:140342326183680  NOTICE: ### [Torrenter v.2.3.7c]: Encryption failed! Exception: 'module' object has no attribute 'pe_settings'
21:56:15 T:140342326183680  NOTICE: ### [Torrenter v.2.3.7c]: Encryption enabling...
21:56:15 T:140342326183680  NOTICE: ### [Torrenter v.2.3.7c]: Encryption failed! Exception: 'module' object has no attribute 'pe_settings'
21:56:15 T:140342326183680  NOTICE: !!!!!!!!!!!!!!!!!! BORN DownloadDB
21:56:15 T:140342326183680  NOTICE: !!!!!!!!!!!!!!!!!! DIED !!! DownloadDB
21:56:15 T:140342326183680  NOTICE: !!!!!!!!!!!!!!!!!! DIED !!! Torrent
21:56:15 T:140342326183680  NOTICE: !!!!!!!!!!!!!!!!!! DIED !!! Libtorrent
21:56:15 T:140342326183680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: downloads
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.torrenter/default.py", line 40, in <module>
                                                core.executeAction(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1041, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1668, in downloadLibtorrent
                                                torrent.downloadProcess(ind, encryption)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Downloader.py", line 105, in downloadProcess
                                                return self.player.downloadProcess(contentId, encrytion)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Libtorrent.py", line 306, in downloadProcess
                                                self.storageDirectory)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/functions.py", line 1469, in add
                                                if not self.get(title):
                                              File "/storage/.kodi/addons/plugin.video.torrenter/functions.py", line 1425, in get
                                                self._connect()
                                              File "/storage/.kodi/addons/plugin.video.torrenter/functions.py", line 1538, in _connect
                                                self.cur.execute('drop table downloads')
                                            OperationalError: no such table: downloads
                                            -->End of Python script error report<--
```
The same error occurs when trying to open 'Download Status' entry

**Comment by bam80** [comment]
Workaround:
```
# rm -r .kodi/temp/xbmcup/plugin.video.torrenter/
```

**Comment by DiMartinoXBMC** [comment]
https://github.com/DiMartinoXBMC/plugin.video.torrenter/commit/acc41a09f5fb86211597bcc8a1040deb1e029fbc should fix that
