### ISSUE TITLE
Content lists IMDB

### ISSUE THREAD

**Issue by Gregsr** [DiMartinoXBMC/plugin.video.torrenter#6]
First, thanks for updates about T...FR searcher discussed on forum.kodi last week. It works fine!

IMDB content lists do not work. I have a torrenter script error. Here is log file http://goo.gl/JeBv6e
Thank you for your help
Gregsr

**Comment by DiMartinoXBMC** [comment]
Log is not complete, please provide a new one.

**Comment by Gregsr** [comment]
Sorry. It will be "easier" with this http://goo.gl/DDDM4J :)

**Comment by DiMartinoXBMC** [comment]
hm, this is memory error, I'll try something

18:23:46 T:1851423392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: disk I/O error
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/default.py", line 40, in <module>
                                                core.executeAction(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 1046, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 631, in openContent
                                                self.draw(apps, mode='content')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 664, in draw
                                                self.drawcontentList(contentList)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/Core.py", line 799, in drawcontentList
                                                meta = self.Scraper.scraper(scraper, {'label': title, 'search': search, 'year': year}, self.language)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/resources/scrapers/scrapers.py", line 99, in scraper
                                                scraper_item = scraper.scraper(search, year)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/resources/scrapers/tvdb.py", line 60, in scraper
                                                return self.movie(id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/resources/scrapers/tvdb.py", line 68, in movie
                                                return self.cache.get('movie:' + id, self._movie, id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrenter/resources/scrapers/cache.py", line 57, in get
                                                cur.execute('replace into cache(id,addtime,expire,data) values(?,?,?,?)', (token, curtime, None, obj))
                                            OperationalError: disk I/O error

**Comment by Gregsr** [comment]
Ok. Thanks
